apiVersion: v1
kind: Pod
metadata:
  name: minihelpdesk
  labels:
    app: web
spec:
  containers:
    - name: ticketmanagement-api
      image: ledexregistry:55000/minihelpdesk:ci-23
      ports:
        - containerPort: 8080
#apiVersion: v1
#kind: Pod
#metadata:
# name: minihelpdesk
# labels:
# app : api
#spec:
# containers: 
#  - name: ticketmanagement-api
#    image: ledexregistry:55000/minihelpdesk:ci-10
#    ports:
#     - containerport: 8080